version: "3"

services:
  server:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    # command: sh -c "npm install && npm run prod"
    command: >
      bash -c "
        npm install && 
        npm install -g gulp &&
        gulp js &&
        gulp css &&
        npm run prod
      "
